url: https://www.ville-europeenne.org
collections_dir: collections
collections:
  signataires:
    sort_by: ville
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: "admin"
    values:
      sitemap: false
plugins:
  - jekyll-sitemap