collections_dir: collections
url: https://www.ville-europeenne.org
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: "admin"
    values:
      sitemap: false
plugins:
  - jekyll-sitemap