backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
publish_mode: editorial_workflow
media_folder: 'assets/uploads'
collections:
  - name: "config"
    label: "Config"
    editor:
      preview: false
    files:
      - label: "Identité du site"
        name: "identity"
        file: "_data/identity.yml"
        fields:
          - {label: "Titre", name: "name", widget: "string"}
#          - label: "Logo"
#            name: "logo"
#            widget: "image"
#            media_library:
#              config:
#                multiple: false
          - {label: "Profil Twitter", name: "twitter", widget: "string"}
      - label: "Signataires de la charte"
        name: "signataires"
        file: "_data/signataires.yml"
        widget: "list"
        fields:
          - {label: Prénom, name: prenom, widget: string}
          - {label: Nom de famille, name: nom, widget: string}
          - {label: Ville, name: ville, widget: string}
          - {label: Département, name: departement, widget: number, valueType: "int"}
          - {label: Liste, name: liste, widget: string}
          - {label: Étiquette, name: etiquette, widget: string}