backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: 'assets/uploads'
site_url: https://www.ville-europeenne.org
display_url: https://www.ville-europeenne.org
logo_url: https://www.ville-europeenne.org/assets/img/label-ville-europeenne.png
show_preview_links: false
collections:
  - name: 'signataires'
    label: 'Signataires de la charte'
    folder: 'collections/_signataires/'
    create: true
    slug: '{{departement}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Département', name: 'departement', widget: 'string' }
      - { label: 'Nom de la commune', name: 'title', widget: 'string' }
      - label: "Candidats"
        name: "candidats"
        widget: "list"
        fields:
          - {label: "Nom", name: "nom", widget: "string"}
          - {label: "Prénom", name: "prenom", widget: "string"}
          - {label: "Étiquette", name: "etiquette", widget: "string", required: false}
          - {label: "Liste", name: "liste", widget: "string", required: false}