backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
publish_mode: editorial_workflow
media_folder: 'assets/uploads'
collections:
  - name: "config"
    label: "Config"
    editor:
      preview: false
    files:
      - label: "Identité du site"
        name: "identity"
        file: "_data/identity.yml"
        fields:
          - {label: "Titre", name: "name", widget: "string"}
          - label: "Logo"
            name: "logo"
            widget: "image"
            default: "../img/label-ville-europeenne-blanc.png"
            media_library:
              config:
                multiple: true
          - {label: "Profil Twitter", name: "twitter", widget: "string"}
